import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Logo from "@/components/Logo";
import AnimatedNavbar from "@/components/AnimatedNavbar";

const yourFont = localFont({
  src: [
    {
      path: '../fonts/FranieVariableTest-Bold.otf',
      weight: '700',
    },
  ],
  variable: '--font-yourfont',
  display: 'swap', // or 'optional' depending on your needs
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${yourFont.variable} antialiased bg-[#030507] text-white min-h-screen`}
      >
        <div className="fixed inset-0 -z-10 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#B947C7_100%)]"></div>
        <Logo />
        <AnimatedNavbar />
        {children}
      </body>
    </html>
  );
}
